### ISSUE TITLE
Starting Julia ... Error in getJuliaExecutablePath() :    Julia not found in path. Please check your Julia setup.

### ISSUE THREAD

**Issue by ravinder387** [stefan-m-lenz/JuliaConnectoR#3]
I can't run julia even in put julia in .bashrc in ubuntu
what should i do now?

**Comment by stefan-m-lenz** [comment]
How did you install Julia? Can you start Julia on the command line?

**Comment by ravinder387** [comment]
yes.. now it's working in R terminal .. not work on R studio ide. I want to know about JULIA_BINDIR and how to give custom path to julia executable in juliaconnector and How to incrrease performance

**Comment by ravinder387** [comment]
Performance is slow than juliacall..

**Comment by stefan-m-lenz** [comment]
> yes.. now it's working in R terminal .. not work on R studio ide. I want to know about JULIA_BINDIR and how to give custom path to julia executable in juliaconnector and How to incrrease performance

You can set the JULIA_BINDIR to the folder containing the julia executable. Then this Julia version will be used. This has to be set before Julia is started.

You can increase the performance by minimising the number of calls.

I can't comment on why it is not working in RStudio for you because I don't know how you set it up.

**Comment by ravinder387** [comment]
do u mean in .bashrc file  i have to write export JULIA_BINDIR=Julia-1.5/bin  .... I don't know much about linux now
if my code running on Julia jit compiler... why it slower than R. I know in R libraries written in rcpp but atleast my code running speed = C++ function.  why it slower

**Comment by stefan-m-lenz** [comment]
Yes JULIA_BINDIR is an environment variable. You can set it in the Linux shell by writing
    export JULIA_BINDIR=/path/to/julia-XX/bin
or you can set it in R via 
    Sys.setenv(JULIA_BINDIR = "/path/to/julia-XX/bin")

The calls from R to Julia have some overhead. If you have many small calls, it will be slower than writing pure R. Without seeing actual code, I can't tell you more.

**Comment by ravinder387** [comment]
thank you .. Sys.setenv(JULIA_BINDIR = "/path/to/julia-XX/bin") I run this command but I cannot see this in my .bashrc where this JULIA_BINDIR located.. kindly help me

**Comment by ravinder387** [comment]
[](url)

**Comment by ravinder387** [comment]
bench::mark(mean(r))  #time 323 microsecond
bench::mark(j$mean0(r)) #time 7 milisecond

**Comment by stefan-m-lenz** [comment]
> thank you .. Sys.setenv(JULIA_BINDIR = "/path/to/julia-XX/bin") I run this command but I cannot see this in my .bashrc where this JULIA_BINDIR located.. kindly help me

I don't know how you installed Julia, so I don't know where your install location is.

**Comment by stefan-m-lenz** [comment]
> bench::mark(mean(r)) #time 323 microsecond
> bench::mark(j$mean0(r)) #time 7 milisecond

With this you measured mainly the overhead that it takes to communicate with Julia. It doesn't make sense to call to Julia for such simple commands because e.g. the mean function in R is already highly optimized. It only makes sense if you use more time-consuming algorithms where the increased speed compensates the overhead for calling Julia.
