### ISSUE TITLE
Feature Request: When started inside RCall, pick up the existing JuliaSession

### ISSUE THREAD

**Issue by schlichtanders** [stefan-m-lenz/JuliaConnectoR#34]
Hi there, I am trying to integrate R and Julia where my setup first starts Julia and then starts R as a subprocess via RCall.jl

It would be great if JuliaConnectoR could connect to the same julia instance already running, so that defining variables on Julia site will actually show up on the top-level julia process.

**Comment by stefan-m-lenz** [comment]
Hi, RCall.jl and the JuliaConnectoR use completely different mechanisms for communicating between R and Julia. RCall is based on the integration at the C interface while the JuliaConnectoR communicates via TCP, which is slower but more stable across different versions. If you want to use R from Julia, it would make more sense to make this feature request in RCall?

**Comment by schlichtanders** [comment]
Thanks for commenting. This issue is about the special case when JuliaConnectoR is not loaded inside a regular R session, but within an R session which was started by RCall.

Even though RCall and JuliaConnectoR use different communication mechanisms, it would still be awesome if no extra julia process needs to be spawned, but the original one is reused.

**Comment by stefan-m-lenz** [comment]
As you say, it is a very special case. I don't know whether it is worth the effort to implement this. I don't have time for it anyway right now but even if someone else would like to develop it, I'm not sure if I'd merge a solution for it as it adds a lot of complexity with very little gain.

**Comment by schlichtanders** [comment]
Thank you for the information. For my usecase it is indeed key, hence I will rather focus on r-juliacall instead.

Feel welcome to close this issue as "not planned" or similar

**Comment by stefan-m-lenz** [comment]
Alright, I wish you the best of success for this project. As suggested, I will close the issue.

JuliaCall is already tightly integrated with RCall.jl. So it makes sense to focus on JuliaCall in your scenario if it works.

The need for creating the JuliaConnectoR came out of the fact that the JuliaCall package did not work reliably across Julia versions (which still seems to be an issue). Therefore, I started the JuliaConnectoR which relies on connecting via TCP instead of the C connection that JuliaCall and RCall.jl use. Communicating via TCP is slower, but more stable across versions. It also allowed a clean API design that is targeted for a user-friendly experience when calling Julia from R. But with this focus it is less suited to be used in the opposite direction without a major overhaul.

So trying to integrate with RCall would go completely against the basic philosophy of the JuliaConnectoR package and I don't see it happening at the moment.
